name: study-task-env
channels:
  - defaults
dependencies:
  - altair=6.0.0=py310haa95532_1
  - arrow-cpp=21.0.0=h6358905_1
  - attrs=25.4.0=py310haa95532_2
  - aws-c-auth=0.9.0=h02ab6af_2
  - aws-c-cal=0.9.2=h02ab6af_1
  - aws-c-common=0.12.4=h02ab6af_0
  - aws-c-compression=0.3.1=h02ab6af_2
  - aws-c-event-stream=0.5.6=h02ab6af_0
  - aws-c-http=0.10.4=h02ab6af_0
  - aws-c-io=0.21.4=h02ab6af_0
  - aws-c-mqtt=0.13.3=h02ab6af_0
  - aws-c-s3=0.8.7=h02ab6af_0
  - aws-c-sdkutils=0.2.4=h02ab6af_1
  - aws-checksums=0.2.7=h02ab6af_1
  - aws-crt-cpp=0.34.0=h885b0b7_0
  - aws-sdk-cpp=1.11.638=hf0af688_0
  - blas=1.0=mkl
  - blinker=1.9.0=py310haa95532_1
  - bottleneck=1.4.2=py310h540bb41_1
  - brotlicffi=1.2.0.0=py310h885b0b7_0
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.34.5=h731ff69_0
  - ca-certificates=2025.12.2=haa95532_0
  - cachetools=6.2.2=py310haa95532_0
  - certifi=2026.01.04=py310haa95532_0
  - cffi=2.0.0=py310h02ab6af_1
  - charset-normalizer=3.4.4=py310haa95532_0
  - click=8.2.1=py310haa95532_1
  - colorama=0.4.6=py310haa95532_0
  - cycler=0.12.1=py310haa95532_0
  - expat=2.7.3=h885b0b7_4
  - filelock=3.20.0=py310haa95532_0
  - freetype=2.13.3=h0620614_0
  - fsspec=2025.10.0=py310h4442805_0
  - gflags=2.2.2=hd77b12b_1
  - gitdb=4.0.12=py310haa95532_0
  - gitpython=3.1.46=py310haa95532_0
  - glog=0.5.0=hd77b12b_1
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.2=py310h8598115_0
  - idna=3.11=py310haa95532_0
  - importlib-metadata=8.7.0=py310haa95532_0
  - intel-openmp=2025.0.0=haa95532_1164
  - jinja2=3.1.6=py310haa95532_0
  - jpeg=9f=ha349fce_0
  - jsonschema=4.25.0=py310haa95532_1
  - jsonschema-specifications=2025.9.1=py310haa95532_0
  - kiwisolver=1.4.9=py310h03f52e7_0
  - lcms2=2.16=hb4a4139_0
  - lerc=3.0=hd77b12b_0
  - libabseil=20250127.0=cxx17_h52369b4_0
  - libbrotlicommon=1.0.9=h827c3e9_9
  - libbrotlidec=1.0.9=h827c3e9_9
  - libbrotlienc=1.0.9=h827c3e9_9
  - libcurl=8.17.0=h97e0424_0
  - libdeflate=1.17=h2bbff1b_1
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libgrpc=1.71.0=hf4237ab_0
  - libhwloc=2.12.1=default_hfa10c62_1000
  - libiconv=1.16=h2bbff1b_3
  - libpng=1.6.50=h46444df_0
  - libprotobuf=5.29.3=h65a231f_1
  - libre2-11=2024.07.02=h5da7b33_0
  - libssh2=1.11.1=h2addb87_0
  - libthrift=0.22.0=ha2884a9_0
  - libtiff=4.5.1=hd77b12b_0
  - libtorch=2.7.0=cpu_mkl_h017a133_100
  - libuv=1.48.0=h827c3e9_0
  - libwebp-base=1.6.0=hbf3958f_0
  - libxml2=2.13.9=h6201b9f_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=3.0.2=py310h827c3e9_0
  - matplotlib-base=3.10.7=py310h26e45b9_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py310h0b37514_0
  - mkl_fft=2.1.1=py310h300f80d_0
  - mkl_random=1.3.0=py310ha5e6156_0
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpmath=1.3.0=py310haa95532_0
  - narwhals=2.7.0=py310haa95532_0
  - networkx=3.4.2=py310haa95532_0
  - numexpr=2.14.1=py310h7660c64_0
  - numpy=1.26.4=py310h12f7302_1
  - numpy-base=1.26.4=py310he4e2855_1
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.0.18=h543e019_0
  - opentelemetry-api=1.38.0=py310haa95532_0
  - orc=2.2.0=hf43e1a1_0
  - packaging=25.0=py310haa95532_1
  - pandas=2.3.3=py310h42c1672_1
  - pip=25.3=pyhc872135_0
  - protobuf=5.29.3=py310h5da7b33_0
  - pycparser=2.23=py310haa95532_0
  - pysocks=1.7.1=py310haa95532_1
  - python=3.10.19=h981015d_0
  - python-dateutil=2.9.0post0=py310haa95532_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - pytorch=2.7.0=cpu_mkl_py310he241c65_100
  - pytz=2025.2=py310haa95532_0
  - pyyaml=6.0.3=py310hb9a58be_0
  - re2=2024.07.02=h214f63a_0
  - referencing=0.37.0=py310haa95532_0
  - requests=2.32.5=py310haa95532_1
  - rpds-py=0.28.0=py310h114bc41_0
  - seaborn=0.13.2=py310haa95532_3
  - six=1.17.0=py310haa95532_0
  - sleef=3.5.1=h8cc25b3_2
  - smmap=5.0.2=py310haa95532_0
  - snappy=1.2.2=hab6b7b3_1
  - sqlite=3.51.1=hda9a48d_0
  - streamlit=1.52.2=py310haa95532_0
  - sympy=1.14.0=py310haa95532_1
  - tbb=2022.3.0=h90c84d6_0
  - tbb-devel=2022.3.0=h90c84d6_0
  - tenacity=9.1.2=py310haa95532_1
  - tk=8.6.15=hf199647_0
  - toml=0.10.2=pyhd3eb1b0_0
  - torchvision=0.15.2=cpu_py310h7187fe4_0
  - tornado=6.5.4=py310h02ab6af_0
  - typing-extensions=4.15.0=py310haa95532_0
  - typing_extensions=4.15.0=py310haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - utf8proc=2.6.1=h2bbff1b_1
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - watchdog=6.0.0=py310haa95532_0
  - wheel=0.45.1=py310haa95532_0
  - win_inet_pton=1.1.0=py310haa95532_1
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zipp=3.23.0=py310haa95532_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - arabic-reshaper==3.0.0
      - astunparse==1.6.3
      - beautifulsoup4==4.14.3
      - blosc2==3.12.2
      - contourpy==1.3.2
      - cryptography==46.0.3
      - decorator==5.2.1
      - elementpath==5.1.0
      - esprima==4.0.1
      - et-xmlfile==2.0.0
      - ffpyplayer==4.5.3
      - fonttools==4.61.1
      - freetype-py==2.5.1
      - future==1.0.0
      - gevent==25.5.1
      - git-filter-repo==2.47.0
      - greenlet==3.3.0
      - imageio==2.37.2
      - imageio-ffmpeg==0.6.0
      - jedi==0.19.2
      - json-tricks==3.17.3
      - markdown-it-py==4.0.0
      - matplotlib==3.10.8
      - mdurl==0.1.2
      - meshpy==2025.1.1
      - moviepy==2.2.1
      - msgpack==1.1.2
      - msgpack-numpy==0.4.8
      - ndindex==1.10.1
      - opencv-python==4.12.0.88
      - openpyxl==3.1.5
      - parso==0.8.5
      - pillow==11.3.0
      - platformdirs==4.5.1
      - proglog==0.1.12
      - psutil==7.2.1
      - psychopy==2025.2.3
      - psychtoolbox==3.0.19.14
      - py-cpuinfo==9.0.0
      - pyarrow==22.0.0
      - pyglet==1.4.11
      - pyparallel==0.2.2
      - pyparsing==3.3.1
      - pypiwin32==223
      - pyqt6==6.10.1
      - pyqt6-qt6==6.10.1
      - pyqt6-sip==13.10.3
      - pyserial==3.5
      - python-bidi==0.6.7
      - python-dotenv==1.2.1
      - python-gitlab==7.1.0
      - python-vlc==3.0.11115
      - pywin32==311
      - pywinhook==1.6.2
      - pyzmq==27.1.0
      - questplus==2023.1
      - requests-toolbelt==1.0.0
      - scipy==1.14.1
      - setuptools==70.3.0
      - soundfile==0.13.1
      - soupsieve==2.8.1
      - tables==3.10.1
      - tqdm==4.67.1
      - ujson==5.11.0
      - urllib3==2.6.2
      - websockets==15.0.1
      - wxpython==4.2.4
      - xarray==2025.6.1
      - xmlschema==4.3.0
      - zope-event==5.0
      - zope-interface==7.2
